// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// make_altrep_scaffold
SEXP make_altrep_scaffold(SEXP x);
RcppExport SEXP _CustomSerialization_make_altrep_scaffold(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(make_altrep_scaffold(x));
    return rcpp_result_gen;
END_RCPP
}
// altrep_scaffold_data
SEXP altrep_scaffold_data(SEXP x);
RcppExport SEXP _CustomSerialization_altrep_scaffold_data(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(altrep_scaffold_data(x));
    return rcpp_result_gen;
END_RCPP
}
// marshall_dispatch
SEXP marshall_dispatch(SEXP x);
RcppExport SEXP _CustomSerialization_marshall_dispatch(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(marshall_dispatch(x));
    return rcpp_result_gen;
END_RCPP
}
// unmarshall_dispatch
SEXP unmarshall_dispatch(SEXP x);
RcppExport SEXP _CustomSerialization_unmarshall_dispatch(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(unmarshall_dispatch(x));
    return rcpp_result_gen;
END_RCPP
}
// c_make_map
XPtr<std::map<std::string, std::string>> c_make_map(List data);
RcppExport SEXP _CustomSerialization_c_make_map(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(c_make_map(data));
    return rcpp_result_gen;
END_RCPP
}
// c_add_map
void c_add_map(XPtr<std::map<std::string, std::string>> map, List data);
RcppExport SEXP _CustomSerialization_c_add_map(SEXP mapSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::traits::input_parameter< XPtr<std::map<std::string, std::string>> >::type map(mapSEXP);
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    c_add_map(map, data);
    return R_NilValue;
END_RCPP
}
// c_export_map_data
List c_export_map_data(XPtr<std::map<std::string, std::string>> map);
RcppExport SEXP _CustomSerialization_c_export_map_data(SEXP mapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< XPtr<std::map<std::string, std::string>> >::type map(mapSEXP);
    rcpp_result_gen = Rcpp::wrap(c_export_map_data(map));
    return rcpp_result_gen;
END_RCPP
}
// c_print_map
void c_print_map(XPtr<std::map<std::string, std::string>> map);
RcppExport SEXP _CustomSerialization_c_print_map(SEXP mapSEXP) {
BEGIN_RCPP
    Rcpp::traits::input_parameter< XPtr<std::map<std::string, std::string>> >::type map(mapSEXP);
    c_print_map(map);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CustomSerialization_make_altrep_scaffold", (DL_FUNC) &_CustomSerialization_make_altrep_scaffold, 1},
    {"_CustomSerialization_altrep_scaffold_data", (DL_FUNC) &_CustomSerialization_altrep_scaffold_data, 1},
    {"_CustomSerialization_marshall_dispatch", (DL_FUNC) &_CustomSerialization_marshall_dispatch, 1},
    {"_CustomSerialization_unmarshall_dispatch", (DL_FUNC) &_CustomSerialization_unmarshall_dispatch, 1},
    {"_CustomSerialization_c_make_map", (DL_FUNC) &_CustomSerialization_c_make_map, 1},
    {"_CustomSerialization_c_add_map", (DL_FUNC) &_CustomSerialization_c_add_map, 2},
    {"_CustomSerialization_c_export_map_data", (DL_FUNC) &_CustomSerialization_c_export_map_data, 1},
    {"_CustomSerialization_c_print_map", (DL_FUNC) &_CustomSerialization_c_print_map, 1},
    {NULL, NULL, 0}
};

void init_CustomSerialization(DllInfo* dll);
RcppExport void R_init_CustomSerialization(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    init_CustomSerialization(dll);
}
