# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_altrep_scaffold <- function(x) {
    .Call(`_CustomSerialization_make_altrep_scaffold`, x)
}

altrep_scaffold_data <- function(x) {
    .Call(`_CustomSerialization_altrep_scaffold_data`, x)
}

marshall_dispatch <- function(x) {
    .Call(`_CustomSerialization_marshall_dispatch`, x)
}

unmarshall_dispatch <- function(x) {
    .Call(`_CustomSerialization_unmarshall_dispatch`, x)
}

c_make_map <- function(data) {
    .Call(`_CustomSerialization_c_make_map`, data)
}

c_add_map <- function(map, data) {
    invisible(.Call(`_CustomSerialization_c_add_map`, map, data))
}

c_export_map_data <- function(map) {
    .Call(`_CustomSerialization_c_export_map_data`, map)
}

c_print_map <- function(map) {
    invisible(.Call(`_CustomSerialization_c_print_map`, map))
}

